version: "3"

services:
  database:
    image: mariadb:latest
    command:
      - "mysqld"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-app}
      MYSQL_USER: ${DATABASE_USER:-app}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-nopassword}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-nopassword}
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql

  php:
    depends_on:
      - database
    build:
      context: ./php
    working_dir: /app/code
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-secret}
      DATABASE_URL: mysql://${DATABASE_USER:-root}:${DATABASE_PASSWORD:-nopassword}@database:3306/${DATABASE_NAME:-app}?serverVersion=5.7
    volumes:
      - ..:/app

  nginx:
    depends_on:
      - php
    image: nginx:latest
    volumes:
      - ../code/public:/app/code/public
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"